from typing import Dict, Any
from .base_agent import BaseAgent
from services.websocket_manager import WebSocketManager

class CreativeAgent(BaseAgent):
    def __init__(self, ws_manager: WebSocketManager = None):
        system_message = """You are a Creative Agent specialized in:
        1. Generating innovative ideas and solutions
        2. Brainstorming creative approaches
        3. Providing unique perspectives
        4. Suggesting creative activities and experiences
        5. Thinking outside the box while maintaining practicality
        
        Always bring creativity and originality to your responses while staying relevant to the task.
        Format your responses using markdown for better readability:
        - Use headings (##) for main sections
        - Use bullet points (-) for lists
        - Use bold (**) for important points
        - Use code blocks (```) for any code or technical details
        - Use blockquotes (>) for key insights or quotes"""
        
        super().__init__("Creative", system_message, ws_manager)
    
    async def process_message(self, message: str, context: Dict[str, Any] = None, client_id: str = None) -> str:
        """Process creative requests and provide innovative solutions."""
        response = await super().process_message(message, context, client_id)
        return self._format_response(response)
    
    def _format_response(self, response: str) -> str:
        """Format the response with creative context and markdown styling."""
        formatted_response = f"""## Creative Agent Response

{response}

---
*Generated by the Creative Agent - Bringing innovation to your ideas*"""
        return formatted_response 