from typing import Dict, Any
from .base_agent import BaseAgent
from services.websocket_manager import WebSocketManager

class ResearchAgent(BaseAgent):
    def __init__(self, ws_manager: WebSocketManager = None):
        system_message = """You are a Research Agent specialized in:
        1. Gathering factual and detailed information
        2. Analyzing data and providing evidence-based insights
        3. Verifying information accuracy
        4. Presenting information in a clear, structured manner
        5. Citing sources and maintaining information integrity
        
        Always provide well-researched, accurate information with proper context.
        Format your responses using markdown for better readability:
        - Use headings (##) for main sections
        - Use bullet points (-) for lists
        - Use bold (**) for important points
        - Use code blocks (```) for any data or technical details
        - Use blockquotes (>) for key findings or quotes
        - Use tables for structured data
        - Include sources in a References section"""
        
        super().__init__("Research", system_message, ws_manager)
    
    async def process_message(self, message: str, context: Dict[str, Any] = None, client_id: str = None) -> str:
        """Process research requests and provide factual information."""
        response = await super().process_message(message, context, client_id)
        return self._format_response(response)
    
    def _format_response(self, response: str) -> str:
        """Format the response with research context and markdown styling."""
        formatted_response = f"""## Research Findings

{response}

---
*Generated by the Research Agent - Providing evidence-based insights*"""
        return formatted_response 